### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by dewanshrawat15** [dewanshrawat15/Lucy#1]
- Save data to collection with a specific user ID node
- Fetch data from Firestore specific to user ID node's

**Comment by mhadaily** [comment]
can I take this @dewanshrawat15 ?

**Comment by dewanshrawat15** [comment]
Sure @mhadaily

**Comment by dewanshrawat15** [comment]
@mhadaily since there's been no update I'm marking this issue as closed.
